kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-pv-1
  labels:
    type: local-zk
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/k8s/zookeeper/log
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: zk-node
          operator: In
          values:
          - "true"
  
