apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ace-ventura-argo
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ace-ventura.net
    http:
      paths:
      - path: /argo
        backend:
          serviceName: argo-ui
          servicePort: 80

