kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv-3
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/minio"
