kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-1
  labels:
    type: local-kafka
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/k8s/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kafka-node
          operator: In
          values:
          - "true"
  
